services:
  # FastAPI service
  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: heart-disease-api
    ports:
      - "8000:8000"

  # Streamlit service
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: heart-disease-web-app
    ports:
      - "8501:8501"
    depends_on: 
      - api   